config/routes.rb
Rails.application.routes.draw do

  resources :ratings

  resources :tools
  resources :tool_listings, only: [:create, :destroy]

  resources :skills
  resources :skill_listings, only: [:create, :destroy] do
      resources :ratings
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

  root 'home#index'

  match '/faq', to: 'home#faq', via: 'get'

  match '/how_it_works', to: 'home#how_it_works', via: 'get'

  match '/contact_us', to: 'home#contact_us', via: 'get'

end

app/models/skill_listing.rb
class SkillListing < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
  has_many :ratings
end

app/controllers/skill_listings_controller.rb
class SkillListingsController < ApplicationController
  before_action :set_skill_listing, only: [:destroy]

  # POST /skill_listings
  # POST /skill_listings.json
  def create
    @skill_listing = SkillListing.new(skill_id: params[:id], user_id: current_user.id)

    respond_to do |format|
      if @skill_listing.save
        format.html { redirect_to current_user, notice: 'Skill listing was successfully created.' }
        format.json { render :show, status: :created, location: @skill_listing }
      else
        format.html { render :new }
        format.json { render json: @skill_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_listings/1
  # DELETE /skill_listings/1.json
  def destroy
    @skill_listing.destroy
    respond_to do |format|
      format.html { redirect_to skill_listings_url, notice: 'Skill listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_listing
      @skill_listing = SkillListing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_listing_params
      params[:skill_listing]
    end
end

app/helpers/skill_listings_helper.rb
module SkillListingsHelper
end

app/views/skill_listings/_form.html.erb
<%= form_for(@skill_listing) do |f| %>
  <% if @skill_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_listing.errors.count, "error") %> prohibited this skill_listing from being saved:</h2>

      <ul>
      <% @skill_listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skill_listings/edit.html.erb
<h1>Editing skill_listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_listing %> |
<%= link_to 'Back', skill_listings_path %>

app/views/skill_listings/index.html.erb
<h1>Listing skill_listings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_listings.each do |skill_listing| %>
      <tr>
        <td><%= link_to 'Show', skill_listing %></td>
        <td><%= link_to 'Edit', edit_skill_listing_path(skill_listing) %></td>
        <td><%= link_to 'Destroy', skill_listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill listing', new_skill_listing_path %>

app/views/skill_listings/new.html.erb
<h1>New skill_listing</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_listings_path %>

app/views/skill_listings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_skill_listing_path(@skill_listing) %> |
<%= link_to 'Back', skill_listings_path %>